// Standalone (no Hardhat) trade executor for the agent loop — reuses the same swapBuilder
// and PolicyVault ABI as contracts/scripts/execute-trade.js, but callable directly from
// helm/lib without spinning up Hardhat's toolchain, since the agent loop just needs to
// interact with an already-deployed contract, not develop/test one.
import { ethers } from "ethers";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { buildSwapTx } from "./swapBuilder.js";
import { toBaseUnits } from "./okxClient.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const MAINNET_RPC = "https://xlayerrpc.okx.com";
const VAULT_ABI = [
  "function agent() view returns (address)",
  "function executeTrade(address,address,uint256,address,address,bytes) external returns (uint256)",
  "event TradeExecuted(address indexed fromToken, address indexed toToken, uint256 amountIn, uint256 amountOut)",
];

function loadAgentPrivateKey() {
  // Prefer process.env first — that's what's populated in a real deployment (Vercel
  // dashboard env vars, no filesystem access to contracts/.env at all there). Only a
  // Vercel deployment exercises this path; local dev and the CLI scripts always have
  // process.env.AGENT_PRIVATE_KEY populated already (via dotenv), so this fallback isn't
  // dead code in one environment or the other.
  if (process.env.AGENT_PRIVATE_KEY) {
    return process.env.AGENT_PRIVATE_KEY;
  }
  // Local fallback: read contracts/.env directly (generated by generate-agent-wallet.js),
  // for callers that haven't already loaded it into process.env themselves.
  const envPath = path.join(__dirname, "..", "contracts", ".env");
  const raw = fs.readFileSync(envPath, "utf8");
  const line = raw.split(/\r?\n/).find((l) => l.startsWith("AGENT_PRIVATE_KEY="));
  if (!line) throw new Error("AGENT_PRIVATE_KEY not found in process.env or contracts/.env");
  return line.slice("AGENT_PRIVATE_KEY=".length).replace(/^"|"$/g, "");
}

/// Executes a real swap through the vault. Throws on any failure — callers must not
/// treat a thrown error as "no trade happened, safe to retry blindly" without inspecting why.
export async function executeTrade({ vaultAddress, fromTokenAddress, fromDecimals, toTokenAddress, amountHuman }) {
  const provider = new ethers.JsonRpcProvider(MAINNET_RPC, 196);
  const agentWallet = new ethers.Wallet(loadAgentPrivateKey(), provider);
  const vault = new ethers.Contract(vaultAddress, VAULT_ABI, agentWallet);

  const onChainAgent = await vault.agent();
  if (onChainAgent.toLowerCase() !== agentWallet.address.toLowerCase()) {
    throw new Error(
      `Signer ${agentWallet.address} is not this vault's authorized agent (${onChainAgent}). Refusing to send a transaction that would just revert.`
    );
  }

  const amount = toBaseUnits(amountHuman, fromDecimals);
  const swap = await buildSwapTx({ vaultAddress, fromTokenAddress, toTokenAddress, amount });

  const tx = await vault.executeTrade(
    fromTokenAddress,
    toTokenAddress,
    amount,
    swap.approveTarget,
    swap.swapTarget,
    swap.swapCalldata
  );
  const receipt = await tx.wait();
  if (receipt.status !== 1) {
    throw new Error(`executeTrade transaction failed on-chain: ${tx.hash}`);
  }

  const event = receipt.logs.map((log) => {
    try {
      return vault.interface.parseLog(log);
    } catch {
      return null;
    }
  }).find((e) => e?.name === "TradeExecuted");

  return {
    txHash: tx.hash,
    amountIn: event?.args.amountIn,
    amountOut: event?.args.amountOut,
  };
}
